import React,{useEffect,useState} from 'react'
import { Card, Form, Loader } from '../components'

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post.id} {...post}/>)
    )
  }

  return (
    <h2 className='mt-5 font-bold text-[#6469ff] text-xl uppercase'>{ title}</h2>
  )
}
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null)
  
  
  return (
    <section className='max-w-7x1 mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'> Browse through a collection of imaginatve and visually stunning images generated by DALL-E AI</p>
      </div>
    </section>
  )
}

export default Home
